package mortgages.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "weight")
	private java.lang.Integer weight;
	@org.kie.api.definition.type.Label(value = "BMI")
	private java.lang.Integer BMI;
	@org.kie.api.definition.type.Label(value = "height")
	private java.lang.Integer height;

	public Person() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getWeight() {
		return this.weight;
	}

	public void setWeight(java.lang.Integer weight) {
		this.weight = weight;
	}

	public java.lang.Integer getBMI() {
		return this.BMI;
	}

	public void setBMI(java.lang.Integer BMI) {
		this.BMI = BMI;
	}

	public java.lang.Integer getHeight() {
		return this.height;
	}

	public void setHeight(java.lang.Integer height) {
		this.height = height;
	}

	public Person(java.lang.Integer age, java.lang.Integer weight,
			java.lang.Integer BMI, java.lang.Integer height) {
		this.age = age;
		this.weight = weight;
		this.BMI = BMI;
		this.height = height;
	}

}